// VuePiano/src/components/PanelTempo.vue
<template lang="pug">
PanelTemplate(title="Tempo (bpm)")
  template(v-slot)
    .container
      input#tempo(v-model='tempo' type='range' name='tempo' min='1' max='240' step='1')
      input#tempo(v-model='tempo' type='number' name='tempoInput') 

</template>

<script>
import { inject, ref } from 'vue';
import PanelTemplate from './PanelTemplate.vue';

export default {
  name: 'PanelTempo',
  components: {
    PanelTemplate,
  },
  setup() {
    const engine = inject('engine');
    return { engine, tempo: ref(120) };
  },
  mounted() {
    this.engine.on('tempoChange', (tempo) => {
      this.tempo = tempo
    })
  },
  watch: {
    tempo(newVal) {
      this.engine.tempoChange(newVal);
    },
  },
};
</script>

<style>
.container {
  display: flex;
  flex-direction: column;
  justify-content: center;
  align-items: center;
  text-align: center;
}
input[type="range"] {
  margin-right: 10px;
}
input[type="number"] {
  font-size: smaller;
  height: 20px;
  width: 50px;
  margin-top: 5px;
  padding: 5px;
  border-radius: 5px;
  border: none;
}
</style>

// SveltePiano/src/components/Panel/PanelTempo.svelte
<script lang="ts">
  import { onMount, onDestroy } from 'svelte'
  import PanelTemplate from './PanelTemplate.svelte'
  import { musicEvents } from '../../game/EventBroker'
  import Engine from '../../game/Engine'
  
  let tempo = $state(120)
  let unsubscribeReset: (() => void) | null = null

  onMount(() => {
    // Listen to tempo changes from EventBroker instead of engine context
    unsubscribeReset = musicEvents.on('tempo-change', (data: { bpm: number }) => {
      tempo = data.bpm
    })
  })

  onDestroy(() => {
    if (unsubscribeReset) {
      unsubscribeReset()
    }
  })

  function updateTempo() {
    const engineInstance = Engine.instance
    if (engineInstance) {
      engineInstance.tempoChange(tempo)
    }
  }
</script>

<PanelTemplate title="Tempo (bpm)">
  {#snippet children()}
    <div class="container">
      <input 
        id="tempo"
        type="range" 
        name="tempo"
        min="1" 
        max="240"
        step="1"
        bind:value={tempo}
        oninput={updateTempo}
      />
      <input 
        id="tempo-number"
        type="number" 
        name="tempo-number"
        min="1" 
        max="240"
        step="1"
        bind:value={tempo}
        oninput={updateTempo}
      />
    </div>
  {/snippet}
</PanelTemplate>

<style>
  .container {
    display: flex;
    flex-direction: column;
    align-items: center;
    gap: 10px;
  }

  #tempo {
    width: 100%;
  }

  #tempo-number {
    width: 80px;
    text-align: center;
    background-color: #333;
    border: 1px solid #555;
    color: white;
    border-radius: 3px;
    padding: 5px;
  }
</style>
