// VuePiano/src/App.vue
<script>
import ThePanel from '@/components/ThePanel.vue'
import TheKeyboard from '@/components/TheKeyboard.vue'
import TheSheet from '@/components/TheSheet.vue'
import {defineComponent, provide, ref } from 'vue';

export default defineComponent({
  name: 'App',
  components: {
    ThePanel,
    TheSheet,
    TheKeyboard,
  },
  setup() {
    const engine = ref({});
    const isEngineReady = ref(false)
    provide('engine', engine);
    return { engine, isEngineReady };
  },
  methods: {
    assingApp(engine) {
      console.log('The engine is ready', engine);
      this.engine = engine;
      this.isEngineReady = true
      window.engine = engine
    },
  },
});
</script>

<template lang="pug">
#game
  ThePanel(v-if="isEngineReady")
  TheSheet(@engine-ready="assingApp")
  TheKeyboard(v-if="isEngineReady")

</template>

<style>

@media screen and (max-height: 992px) {
  body {
    font-size: 2vh;
  }
}

html, body {
  min-height: 100vh;
  margin: 0;
  padding: 0;
  overflow: hidden;
}
*{
  box-sizing: border-box;
  padding: 0;
  margin: 0;
}

#game {
  display: grid;
  grid-template-columns: 1fr 1fr 1fr 1fr;
  grid-template-rows: 15vh 70vh 15vh;
  grid-template-areas:
    "panel panel panel panel"
    "sheet sheet sheet sheet"
    "keyboard keyboard keyboard keyboard";
}

#panel {
  grid-area: panel;
}
#sheet {
  grid-area: sheet;
  border: solid 1px black;
}
#keyboard {
  grid-area: keyboard;
}
</style>

// SveltePiano/src/App.svelte
<script lang="ts">
  import ThePanel from './components/Panel/ThePanel.svelte'
  import TheKeyboard from './components/Keyboard/TheKeyboard.svelte'
  import TheSheet from './components/Sheet/TheSheet.svelte'
  import { setContext } from 'svelte'

  let engine = $state({})
  let isEngineReady = $state(false)
  
  setContext('engine', {
    get: () => engine,
    set: (value) => { engine = value }
  })

  function assignApp(engineInstance) {
    console.log('The engine is ready', engineInstance)
    engine = engineInstance
    isEngineReady = true
    window.engine = engineInstance
  }
</script>


  <div id="game">
    {#if isEngineReady}
      <ThePanel />
    {/if}
    <TheSheet onEngineReady={assignApp} />
    {#if isEngineReady}
      <TheKeyboard />
    {/if}
  </div>


<style>
  :global(body) {
  min-height: 100vh;
  margin: 0;
  padding: 0;
  overflow: hidden;
}
  #game {
    width: 100vw;
    display: grid;
    grid-template-columns: 1fr 1fr 1fr 1fr;
    grid-template-rows: 15vh 70vh 15vh;
    grid-template-areas:
      "panel panel panel panel"
      "sheet sheet sheet sheet"
      "keyboard keyboard keyboard keyboard";
  }

  :global(#panel) {
    grid-area: panel;
  }

  :global(#sheet) {
    grid-area: sheet;
    border: solid 1px black;
  }

  :global(#keyboard) {
    grid-area: keyboard;
  }

  :global(*) {
    box-sizing: border-box;
    padding: 0;
    margin: 0;
  }

  @media screen and (max-height: 992px) {
    :global(body) {
      font-size: 2vh;
    }
  }
</style>
