// SveltePiano/src/components/TheKeyboard.svelte
<script lang="ts">
  import { onMount, getContext } from 'svelte'
  import Octave from './KeyOctave.svelte'
  import piano from '../game/Piano'
  import keyboardMapping from '../utils/keyboardMapping'
  import { keysToBePressed } from '../game/Note'
  import _ from 'lodash'

  interface Props {
    octaveAmount?: number
    startingOctave?: number
  }

  let { octaveAmount = 7, startingOctave = 2 }: Props = $props()
  
  const engineContext = getContext('engine') as any;
  
  let keyboard: HTMLDivElement
  let octaves: Octave[] = []
  let sheetWidth = $state(null)
  let octaveWidth = $state<null|number>(null) 
  let keyWidth = $state<null|number>(null)
  let availableInputs = $state(null)
  let selectedInput = $state(null)

  const octaveRange = $derived(_.range(startingOctave, startingOctave + octaveAmount))

  onMount(() => {
    octaveWidth = keyboard.offsetWidth / octaveAmount
    keyWidth = octaveWidth / 12

    window.addEventListener('keydown', (e) => {
      if (e.key === 'ArrowLeft') engineContext.get().stepBackward()
      if (e.key === 'ArrowRight') engineContext.get().stepForward()
      if (!keyboardMapping[e.key]) return
      
      const { octave, pitch, midi } = keyboardMapping[e.key]
      if (keysToBePressed.has(midi)) {
        keysToBePressed.delete(midi)
        engineContext.get().keysBeingPressed.add(midi)
        engineContext.get().start()
      }
      piano.keyDown({ midi })
      octaves[octave - 1]?.pressKey(pitch)
    })

    window.addEventListener('keyup', (e) => {
      if (!keyboardMapping[e.key]) return
      const { octave, pitch, midi } = keyboardMapping[e.key]
      piano.keyUp({ midi })
      octaves[octave - 1]?.releaseKey(pitch)
    })

    window.addEventListener('note-on', (e) => {
      const { octave, pitch, midi, velocity } = e.detail
      if (keysToBePressed.has(midi)) {
        keysToBePressed.delete(midi)
        engineContext.get().keysBeingPressed.add(midi)
        engineContext.get().start()
      }
      piano.keyDown({ midi, velocity })
      octaves[octave - 1]?.pressKey(pitch)
    })

    window.addEventListener('note-off', (e) => {
      const { octave, pitch, midi, velocity } = e.detail
      piano.keyUp({ midi, velocity })
      octaves[octave - 1]?.releaseKey(pitch)
    })
  })
</script>

<div id="keyboard" bind:this={keyboard}>
  {#each octaveRange as k, index}
    <Octave 
      bind:this={octaves[index]}
      {octaveWidth}
      {keyWidth}
      octave={k}
    />
  {/each}
</div>

<style>
  #keyboard {
    display: flex;
    margin-top: -5px;
    margin-bottom: 0px;
    background-color: black;
  }
</style>

// VuePiano/src/components/TheKeyboard.vue
<template lang="pug">
#keyboard(ref="keyboard")
  octave(
    v-for='k in octaves'
    ref="octaves"
    :octaveWidth='octaveWidth'
    :keyWidth='keyWidth'
    :key='k'
    :octave='k'
  )
</template>

<script>
import Octave from './KeyOctave.vue';
import WebMidi from 'webmidi';
import piano from '@/game/Piano';
import keyboardMapping from '@/utils/keyboardMapping'
import { keysToBePressed } from '../game/Note';
import _ from 'lodash'

export default {
  name: 'TheKeyboard',
  components: {
    Octave,
  },
  props: {
    octaveAmount: {
      type: Number,
      default: 7,
    },
    startingOctave: {
      type: Number,
      default: 2
    }
  },
  inject: ['engine'],
  data() {
    return {
      sheetWidth: null,
      octaveWidth: null,
      keyWidth: null,
      availableInputs: null,
      selectedInput: null
    };
  },
  computed: {
    octaves() {
      return _.range(this.startingOctave, this.startingOctave + this.octaveAmount)
    }
  },
  mounted() {
    this.octaveWidth = this.$refs.keyboard.offsetWidth / this.octaveAmount;
    this.keyWidth = this.octaveWidth / 12;

    window.addEventListener('keydown', (e) => {
      if (e.key === 'ArrowLeft') this.engine.value.stepBackward()
      if (e.key === 'ArrowRight') this.engine.value.stepForward()
      if (!keyboardMapping[e.key]) return
      const { octave, pitch, midi } = keyboardMapping[e.key];
      if (keysToBePressed.has(midi)) {
        keysToBePressed.delete(midi)
        this.engine.value.keysBeingPressed.add(midi)
        this.engine.value.start()
      }
      piano.keyDown({ midi });
      this.$refs.octaves[octave - 1].$refs[pitch].pressKey();
    });

    window.addEventListener('keyup', (e) => {
      if (!keyboardMapping[e.key]) return
      const { octave, pitch, midi } = keyboardMapping[e.key]
      piano.keyUp({ midi });
      this.$refs.octaves[octave - 1].$refs[pitch].releaseKey();

    });

    window.addEventListener('note-on', (e) => {
      const { octave, pitch, midi, velocity } = e.detail;
      if (keysToBePressed.has(midi)) {
        keysToBePressed.delete(midi)
        this.engine.value.keysBeingPressed.add(midi)
        this.engine.value.start()
      }
      piano.keyDown({ midi, velocity });
      this.$refs.octaves[octave - 1].$refs[pitch].pressKey();
    });

    window.addEventListener('note-off', (e) => {
      const { octave, pitch, midi, velocity } = e.detail;
      piano.keyUp({ midi, velocity });
      this.$refs.octaves[octave - 1].$refs[pitch].releaseKey();
    });
  },
};
</script>

<style>
#keyboard {
  display: flex;
  margin-top: -5px;
  margin-bottom: 0px;
  background-color: black;
}
</style>
