// SveltePiano/src/components/Sheet/TheSheet.svelte
<script lang="ts">
  import { onMount } from 'svelte'
  import initialize from '../../game/Sketch'

  interface Props {
    onEngineReady: (engine: any) => void
  }

  let { onEngineReady }: Props = $props()
  let canvas: HTMLCanvasElement

  onMount(async () => {
    const engine = await initialize(canvas)
    onEngineReady(engine)
  })
</script>

<div id="sheet">
  <canvas bind:this={canvas} style="height: 100%; width: 100%;"></canvas>
</div>

// VuePiano/src/components/TheSheet.vue
<template lang='pug'>
#sheet
  canvas(ref="scene" style="height: 100%; width: 100%;")
</template>

<script>
import initialize from '@/game/Sketch.js';

export default {
  name: 'TheSheet',
  emits: ['engine-ready'],
  data() {
    return {
      noteContainers: null,
    };
  },
  async mounted() {
    initialize(this.$refs.scene).then((engine) => {
      this.$emit('engine-ready', engine);
    });
  },
};
</script>
